{% set name = "SALib" %}
{% set version = "1.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: de0e88d1fd7df5574573c70a0e1933faab136b2845e64d7ad65ebb883e6cc69e

build:
  entry_points:
    - salib = SALib.scripts.salib:main
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - hatch-vcs
    - hatchling
  run:
    - python
    - numpy >=2.0
    - pandas >=2.0
    - scipy >=1.9.3
    - matplotlib-base >=3.5
    - multiprocess
  run_constrained:
    - pathos >=0.3.2

test:
  source_files:
    - tests
    - src/SALib/test_functions
    - pyproject.toml
  requires:
    - pip
    - pytest
  commands:
    - pip check
    # E AssertionError:
    # E Not equal to tolerance rtol=1e-07, atol=0.005
    - pytest -v --ignore=tests/test_discrepancy.py
  imports:
    - SALib

about:
  home: https://github.com/SALib/SALib
  dev_url: https://github.com/SALib/SALib
  doc_url: https://salib.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Sensitivity Analysis Library
  description: |
    Python implementations of commonly used sensitivity analysis methods.
    Useful in systems modeling to calculate the effects of model inputs or
    exogenous factors on outputs of interest.

extra:
  recipe-maintainers:
    - jschueller
    - willu47
    - ConnectedSystems
