{% set version = "1.3.11" %}
package:
  name: salib
  version: {{ version }}
source:
  fn: Salib-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/S/SALib/SALib-{{ version }}.tar.gz
  sha256: af07e284ce1e85d2fea6c571b4b3d5c518f70faa518ed890ca4212bd0ad0d3d8
build:
  number: 0
  noarch: python
  script:
    - "{{ PYTHON }} -m pip install . --no-deps -vv"
requirements:
  build:
    - pyscaffold >=3.2a0,<3.3a0
    - pip
    - python >=3.6
    - setuptools >=38.3
  host:
    - pip
    - python >=3.6
    - setuptools >=38.3
  run:
    - python >=3.6
    - numpy >=1.16
    - pandas >=1.0.3
    - scipy
    - matplotlib-base
test:
  imports:
    - SALib
  requires:
    - pytest
  commands:
    - pytest
about:
  home: http://salib.github.io/SALib/
  license: MIT
  license_file: LICENSE.md
  summary: Sensitivity Analysis Library
extra:
  recipe-maintainers:
    - jschueller
    - willu47
