{% set version = "1.3.11" %}

package:
  name: salib
  version: {{ version }}

source:
  fn: salib-{{ version }}.tar.gz
  url: https://github.com/SALib/SALib/archive/v{{ version }}.tar.gz
  sha256: af07e284ce1e85d2fea6c571b4b3d5c518f70faa518ed890ca4212bd0ad0d3d8

build:
  number: 0
  noarch: python
  script:
    - git init  # hack to build from tarball
    - python -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=30.3.0
  run:
    - python >=3.6
    - numpy >=1.16
    - pandas >=1.0.3
    - scipy
    - matplotlib-base

test:
  imports:
    - SALib
  requires:
    - pytest
  commands:
    - pytest
  

about:
  home: http://salib.github.io/SALib/
  license: MIT
  license_file: LICENSE.md
  summary: Sensitivity Analysis Library


extra:
  recipe-maintainers:
    - jschueller
    - willu47

