{% set version = "1.3.8" %}

package:
  name: salib
  version: {{ version }}

source:
  fn: salib-{{ version }}.tar.gz
  url: https://github.com/SALib/SALib/archive/v{{ version }}.tar.gz
  sha256: 5a20b180400ccbeca27f570c992ed74b69d1ba3653ff328d99821975ec803337

build:
  number: 0
  noarch: python
  script: "python -m pip install . --no-deps -vv"
requirements:
  host:
    - python >=3
    - pip
    - setuptools >=30.3.0
    - pyscaffold >=3.0a0,<3.1a0
  run:
    - python >=3
    - pandas
    - numpy
    - scipy
    - matplotlib

test:
  imports:
    - SALib

about:
  home: http://salib.github.io/SALib/
  license: MIT
  license_file: LICENSE.md
  summary: Sensitivity Analysis Library


extra:
  recipe-maintainers:
    - jschueller
    - willu47
