{% set version = "1.4.7" %}
{% set name = "salib" %}

package:
  name: {{ name }}
  version: {{ version }}
source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e6cb19ec772d6cb7368feceae0f61e51f2d6afdbc4f8986a780b87d657b38cc
build:
  number: 1
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
requirements:
  host:
    - pip
    - python
    - hatchling 1.18
  run:
    - python
    - numpy >=1.20.3
    - pandas >=1.1.2
    - scipy >=1.7.3
    - matplotlib-base >=3.2.2
    - multiprocess
  run_constrained:
    - pathos >=0.2.5

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - SALib

about:
  home: https://github.com/SALib/SALib
  dev_url: https://github.com/SALib/SALib
  doc_url: https://salib.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Sensitivity Analysis Library
  description: |
    Python implementations of commonly used sensitivity analysis methods.
    Useful in systems modeling to calculate the effects of model inputs or
    exogenous factors on outputs of interest.

extra:
  recipe-maintainers:
    - jschueller
    - willu47
    - ConnectedSystems
