travis:
  secure:
    BINSTAR_TOKEN: Zl+V1BxhDqViAiLos+G3Gsgk0M5DerlOdlhV66D+/bWHaLUh87NVi6L5OGOkD72nGy1VM/iTUs5WvnMNy13aYdseOy2GoFX3nL6HREk9FFxQ2EXW9HEW8bjNk7OSgCvb4wgqzES7b3E622LxjHuvnsnIf8wL+m5JQy+xHD4N91xdfkG858ByybRGgWEyMGMwMPB/gAjp9xVkyBj5KZ/5Vkm9Ehd5BvYKl7N4VeQpSMOnS5CaSrq4l3y4Djip8h8VsQNNR1/1kZySuE5PNqOW9pCfF7Q1lFqMZrdAxFHEeePqQsDBGrmwMCY9Pa0wOP7HDibK+BROC0o4E4+YC6P0QYJuFcWa7IYT+Zh6bTi+BTfxLyZe1Nl2yjrS2TEl0UYMY61dcIajbbLGI7QuL8fLuqR509u9b5oeMSHyOnJlYVajOEhmN87dJj8/YOQ+kOBu7d8lEZZOmQpmnFxaKjuu9rYQdXGv4WGN2T6orVUUrVmRpPJLfCHJ2yg0zo7THxV+OKFkSAOJHF6kR1ORB0CMTPJHLHeQ+kT98wmtgw5X24cKu9JEhpPFOrLEO032C/kM8NKWYOGC7KHot6x8HJQq8hWT0Sn4hof8R2WTbhDcyaEbrCv7yx3bofw1Ciq7uIcYMA8ZiGSOblHMSYC6AEnZne/lWy8u9oTj19/pgHg7B0g=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
