travis:
  secure:
    BINSTAR_TOKEN: YEb4TszSG8QD8sCmoFDgPgMDgK2nN90mMut3NYaLobEL3vwld0BAtOMJD9OqgU6HpCIWDDiwrmFiZFl1mIb5kR05TojUs1CPRkmYSQwJxFZ0+6Ol9+slwJ1/iGb/Hmt6upg3E1uaBwmBV6GXnso4tLjwICfUSPUiZFji3DVX+ms5dCEmAUZGux+t5x1VPNFmNRhCsKwY49llEfYynBO8VI0DlwWttAHN2w7+Qcoym/uVDcOgWqVTCHKbfy5xfvJg/D+RTLzEZqbBAbzhKDeM54OAxcz5LfB5AaWiKZ7zvMtP9Lgre36+Q8dT4gC4gaCycvvUJF204v7cfl9epi5gF+xXZlQxIZOi9W0nnLA/e9GFXZK25HOW3kMUQaN4/kI69E7HpTHAf+NtZnKZXpPdFA5cNXzsOwMtq9rP8AiJw0vQlGlsXa2FU2vCzrg6KC8HVx72dddESKFAI3eNacseB/Mt7q1+A9MFCQFm5mJrfRMq/ahS73lgOipx6eVQSB5C8oWqyjq8A+Ly/qXiq5879BCMlhb61W1T1WuvUjhqUYjWrWXs6tQLloHb/hVCVg5Eaxvybr8klfP8mEipunETENw4yfbvsZE/taxqTc3A3iFSP8jnmrgLRol85u4yHgTTMUxPr6fURc3WJN5v7+YjllIfcWxPTNt60bt2BvQWqDU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
