travis:
  secure:
    BINSTAR_TOKEN: OxrlckxKrvxeKyCzbtCOj4PH13FrsWl7YwPNjT1UWw0Bh8benWIb2UfrFL2T+zKTBV44SX/bMMLNMVK5ap39/KOEITYyzyjbF6rPZfNEopy/quB7TzJun5qCu5CzJufYW1UMKIz7PNh2dwqmHIpBt+4lf/QcP+G1CUDYgIxBPLY+W9IbOqdd4lL376KdsPk7tgLR9ZqUGMJUIjnUx5yNUXkBm8g2+gwCd6jvP9nDrXfiMcJPQDOiE1zRq9buJQIo4JU1DcZPvJ2oLEJljiqcN/fZoRZgAgvJ3wNmM4MirChOJAKKjIdRgIvb/qHdvJVal62FTuCJ/6zGx6P+um9uh2usN92PB6jLGWyQaZd5aaosG8TJLSciI2Ty9qh1+tae9l+UgjqTNht11WpFPGlR+MDAwJC0pJGvwyeBa40WXPNFrM6AuaIF/NHFk+0FdCwnNIf3yZaou2oEU1HIhEPeWiNlF3ZOEAiKChnvGDo9LU2vTtz+FiG6GLSXl5K+a3exLTdJ/NPc+1Uu7mHx3kSryTSK5eIc0U86rp5x6QbigrcUAZTLUpbr5LsGwOPaF7il3UJ3nFyefXypOKMgr7rm47f73uojNQzW8jKC03F039b8D9B9W5cYipH7CNPoiez2NrpU9m275iG9+sScVeHvE1g38Fab3tcRBGFYgST8bZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
