travis:
  secure:
    BINSTAR_TOKEN: lKS7gz1wEReSqkhhfeSBaCwJkR2NEmIfcj4EdNKSgflCFt5hgt1nOxV0I0LLHfKiAKTat4ZZbWB9kQkjGKYdXaHyIYcHQx3Cc/y5RlWvYH55FdUTRG8MpCTXrJ2HEG0Vw5ajDh47Fs1a2nHmw5Lp5j/0bAw0WCcReXZOZuGGV2C2F+zvFri3e+jp7v6IDb1v9XIl9YsPtilVs7C5neMDH1XlcwNwkazvQPwXckkBa93qDKK9IiFBNLbW41emfvg7xhPMtlmdEKsnTjv21pFhoiXUQ/b00QYolrPBRHkVgQ24ufJMHCfC8OTzy10hVE9yPqRc4o/vw0NhDCztbnLQzU9xS1kFzCbrvdCOnFWiqZimQL95B2am2EHRGvrMzBhIELs86RVJX1OBDLyZa+PlfbDYkYWDAF/iu1wbWeYll9z7Vt7ipZE3hYH/BKPfn/6g6HTMVrNi0F1KfFiWCVEv97Q1yPFp+qVx5ZrLGwL572jKk8El8TdT/BcclQwEOf+u6hGjF049H/EjRA+Ewiymf1XV2ZLoMlWUSlaMuFWDeCg/BLx5G2GkTAwgWxok3U5F88QQ5YvmtgOGZUaXh8dX6tLnoQ+7ul1VjG9xpNPC+xE2a6d/NsnPOdUXOEUGBauMCLypoXs3iWRDpDKjzprd6xTC87W5tw90O6iOYPk7v9E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
