travis:
  secure:
    BINSTAR_TOKEN: gqBfVmvNeMeDHzWE+AVACl63N94K/ZBztCvGQNh1jEV/VkfyZ7uKZYooCnEn3DS5spguuCoAFV6KcMjMcTVbEmIA9fy1b7NwalMlUODHdm5Lp0SxX8QghnJ6mqLR6e1PPs4PBcjk8pkQbn/6L/mBaDn2pha6ilpj8elMYFkpRocGAZ3zXmX0gKHmkKbceAdo7f0egLZOQaeTdlNZhXhBEMd3Xf93GHRsHknwwDRAiH42ZzRkRuS1zSQYtmHeAg8gbbtI5vgm4JRwxt3I/pj9R6QQGMyTIjsAnYm9FrGNPbnHgCujPlUBpK8s8gtULzpBf4xs5T+1Qk7r+an7y63pJHqM1gOkZ8kNiF100NHPg5pyyMwNd1t6fwFvfS3uB0Kzr/l6LudKMj7srhELtLD0F1QCcmJqcy1daSzJajVE7ThbJR/5T8DiPB4mdIxxh94F6O2jaO1ku4DmqhmUPgczT8m5BdrwOk7LbydCQp3RVWazNA30NCFTH+MpRb37sgJCserzVCDyAVUZEXqa+UK6Kss9rIGMH3kSzNMrkuDV4GXf8CpOUj2WRubsOiMSMsh6fFV2tHm7hOOSlJKNX/beBfoLpXmndi1hnVSawmZ/b55SJAWNK72Yp/IVsSRLQoPbu39UkbyTYNzzcmBJOW6lLvSdohKlOfmSHkAGF7TMnI8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
